default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: postgresql
  database: context_development
  pool: 5
  username: djiang
  password: uhsclass13

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: context_production
  host: localhost
  pool: 5
  username: djiang
  password: <%= ENV["CONTEXT_DEVELOPMENT_PASSWORD"] %>
